steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', 'us-central1-docker.pkg.dev/key-tokenizer-382610/my-repository/patient-image:tag1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/key-tokenizer-382610/my-repository/patient-image:tag1']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'service.yaml']
