steps:
  # Build the Docker image from the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/gcp-demo-1-377213/medical-image', '.' ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/gcp-demo-1-377213/medical-image' ]

  # Deploy the Kubernetes manifest to the cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=medical-data-cluster'
